# Generated by Django 4.1.1 on 2022-10-07 05:38

from django.db import migrations


def forwards_func(apps, schema_editor):
# Get model
    teacher = apps.get_model("mainapp", "CourseTeachers")
    courses = apps.get_model("mainapp", "Courses")

# Create model's objects
    teacher.objects.create(
        pk=1,
        name_first="Альфред",
        name_second="Нуцубидзе",
        day_birth="1990-07-10",
    )
    teacher.objects.create(
        pk=2,
        name_first="Роман",
        name_second="Доржинов",
        day_birth="1988-02-04",
    )
    teacher.objects.create(
        pk=3,
        name_first="Ярослав",
        name_second="Конягин",
        day_birth="1981-12-08",
    )
    teacher.objects.create(
        pk=4,
        name_first="Автандил",
        name_second="Наварский",
        day_birth="1983-05-16",
    )
    teacher.objects.create(
        pk=5,
        name_first="Роза",
        name_second="Уланова",
        day_birth="1986-05-09",
    )
    teacher.objects.create(
        pk=6,
        name_first="Бронислава",
        name_second="Алиева",
        day_birth="1971-01-07",
    )
    teacher.objects.create(
        pk=7,
        name_first="Диана",
        name_second="Попова",
        day_birth="1990-08-25",
    )


def reverse_func(apps, schema_editor):
# Get model
    teacher = apps.get_model("mainapp", "CourseTeachers")
# Delete objects
    teacher.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_news_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
