# Generated by Django 4.1.1 on 2022-10-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_courseteachers_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("course", "num")},
        ),
    ]
